### ISSUE TITLE
[Feature request] implement QuineMcClusky algortihm

### ISSUE THREAD

**Issue by axkr** [logic-ng/LogicNG#12]
Could you please provide an implementation of the [Wikipedia  - Quine–McCluskey algorithm](https://en.wikipedia.org/wiki/Quine%E2%80%93McCluskey_algorithm) 

For example the [python-boolean project](https://github.com/hgomersall/python-boolean) (QM.py) code can be ported to Java. There's also a [related blog entry](https://shiftlock.wordpress.com/2011/05/17/quine-mccluskey-algorithm-implementation-in-python/) available.

See also: [Wikipedia - Petrick's method](https://en.wikipedia.org/wiki/Petrick%27s_method)

**Comment by czengler** [comment]
In a very early (unreleased) version of LogicNG I had a very simple version of Quine-McCluskey but was not happy with it.  So I never released it.  Right now I am working on a new implementation of QMC but I cannot promise that it will make the 1.4 release in June or July, but I do my best.  I will keep you updated here.

**Comment by axkr** [comment]
This sounds very good. Thank you very much.

**Comment by czengler** [comment]
OK - I implemented Quine-McCluskey.  You can take a look at it in the `development` branch.  There is the class `QuineMcCluskeyAlgorithm` where you have three possibilities to compute QMC:

1. Give it a formula.  It will then compute the canonical DNF of this formula and compute QMC afterwards.
2. Give it a formula and a list of relevant variables.  It will then compute the canonical DNF of this formula for the relevant variables (projected model enumeration) and compute QMC afterwards.
3. Give it a canonical DNF as list of assignments.  It will then compute QMC directly on this canonical DNF.

The implementation is reasonable efficient (with a nice MaxSAT formulation to determine an optimal coverage of the minterms by prime implicants as a last step).  But of cource: QMC has its boundaries and it will take very long for large canonical DNFs.

We welcome your feedback.  The plan is to release 1.4. in the beginning of May - so any feedback up til then could perhaps be incorporated.

**Comment by axkr** [comment]
Do you have a Snapshot available through Maven pom mechanism?

**Comment by czengler** [comment]
currently we do not deploy Snapshots via Maven Central.

**Comment by czengler** [comment]
QMC does not yield unique results.  When there are equally good results (in terms of number of minterms in the result) one is chosen.  This does not have to be the same as wolframalpha and there is absolutely no way to ensure that the results are comparable with WolframAlpha and we have no intention of doing so.
