### ISSUE TITLE
Set support, Forall / Exists / Element of

### ISSUE THREAD

**Issue by HugoRiggs** [logic-ng/LogicNG#13]
Could there be support for the set based operators: ∀,∃, ∈, ∪? Great library!

**Comment by SHildebrandt** [comment]
Sorry for the delayed response. If I understand your wish correctly, this would require to "lift" LogicNG from propositional logic to first-order logic which would be a huge amount of work. Right now we're not intending to support first-order logic.

Depending on your use case, you might be able to simulate some of the operations with your own formula predicates or formula functions.

**Comment by HugoRiggs** [comment]
Okay I see. Asked because I was trying to convert first-order logic formulas, which included those symbols above, into DNF. As I recall from logic that involves the foreach and exists symbols to be swapped during factorization along with moving not symbols.
