### ISSUE TITLE
miniSat.enumerateAllModels() returns assignments with additional variables

### ISSUE THREAD

**Issue by abdelal** [logic-ng/LogicNG#21]
assignments returned from miniSat.enumerateAllModels() contain variables with name pattern @RESERVED_CC_*

**Comment by d-bischoff** [comment]
use this instead:

miniSat.enumerateAllModels(collectionOfVariablesThatYouAreInteresetedIn)

**Comment by rouven-walter** [comment]
Per default the SAT solver creates models with auxiliary variables included. You can either change the SAT solver's configuration to not include auxiliary variables (see parameter `auxiliaryVariablesInModels` in class `MiniSatConfig) or, as previously described, pass the relevant variables as argument to `enumerateAllModels`.

With version 2.0 of LogicNG the default for auxiliary variables in models changes, such that a model does not contain auxiliary variables.
