### ISSUE TITLE
Performance of QMC 

### ISSUE THREAD

**Issue by yanntm** [logic-ng/LogicNG#23]
Hi,
should calling QMC on this really crash it ? I understand there are many variables, but still.
```
(a0 | a1) & (a2 | a3) & (a4 | a5) | (a6 | a7) & (a8 | a9) | a10 | a11 | a12
```
Would there be a way to detect and throw/exit when the algorithm is going haywire ? e.g. a timeout or max rewritten size or such added to the QMC API. That would be nicer than wrapping invocations with a thread + external timeout, which is what I'm currently considering.

**Comment by czengler** [comment]
Hi, 

QMC works on the canonical DNF of the formula.  Your formula - simple as it may seem - has **7933 minterms** in the canonical DNF.  QMC's performance can get pretty bad very fast. It has to compute all prime implicants of the formula - these can be up to `3^n*ln(n)` - in you case with 13 variables and almost no restrictions on the variables, these can be **over 4 million prime implicants**.  Even if these could be computed, the next step would be to solve the set cover problem on these (which is itself NP-hard)... 

So to cut a long story short: Unfortunately, I do not think, that our implementation of QMC can compute a result on your input formula.  We use this implementation in some industrial applications, but there we have formulas, where we usually have few minterms in the canonical DNF.  But for large formulas, this implementation - and in my personal opinion, QMC in general - is not suited.

Do you really need a DNF as a result?  There are other ways to simplify a formula, e.g. converting it to a BDD with the FORCE heuristics or using some of the other simplifying methods in LogicNG (Backbone Simplification, Distribution, Unit Propagation, ...).  But for your example (a CNF), I would say, your formula is already syntactical minimal - every variable occurs exactly once - there is no way, you could minimize this formula syntactically any further ;)

**Comment by czengler** [comment]
Hey... indeed, after 24 Minutes, QMC yielded a result on your input formula - but as already mentioned: your formula was already syntactical minimal, so the QMC result will most likely not please you ;)

```
a1 & a2 & a4 | a0 & a2 & a4 | a1 & a3 & a5 | a1 & a2 & a5 | a0 & a3 & a4 | a0 & a2 & a5 | a1 & a3 & a4 | a0 & a3 & a5 | a6 & a9 | a7 & a9 | a7 & a8 | a6 & a8 | a10 | a11 | a12
```

**Comment by axkr** [comment]
So an option to set the maximum number of minterms may be a solution to restrict the execution  time?

**Comment by czengler** [comment]
We generally do not want to restrict the user in the possibilities.  The QMC implementation can take the list of assignments as returned by the canonical model enumeration of the SAT solver (`enumerateAllModels`) or the BDD implementation as input. 

So the user can first compute the canonical DNF and then decide in his program code, if she wants to compute QMC or not. What we could however provide would be a custom Handler (like for CNF/DNF computation or SAT solving) where the algorithm can be provided with a handler implemented by the user which can abort the execution of the algorithm.  So here one could use a e.g. a timer for aborting the algorithm after a certain execution time.

**Comment by yanntm** [comment]
Thank you for the detailed answer, I kind of suspected some exponential on the number of variables, but I didn't think it would be `3^n ln(n)`. I've switched to using the canonical DNF, which does most of the simplifications I wanted anyway, and is not too expensive on my inputs.
Indeed nice remark, nothing to go for in terms of syntactic reduction if the variables only occur once in the DNF, I can check for that condition.
I'm a bit reluctant to go for BDD, because it's so difficult to predict when they will work well or a contrario explode. I'll look at the other algorithms you mentioned (Backbone Simplification, Distribution, Unit Propagation, ...). At this point I'd like to start from the DNF and fuse things like `a1 & a2 | a1 & a3` into `a1 & (a2 | a3)`, but not being too naïve would be nice, since in general there are many such possible factorization.
Thanks again for the software and answers, I'll close this issue, your answer is pretty plain, QMC is simply not what I need here.
