### ISSUE TITLE
Is there xor?

### ISSUE THREAD

**Issue by exander77** [logic-ng/LogicNG#26]
Hello, is there a xor operation? I am unable to find it.

**Comment by rouven-walter** [comment]
Hello, no, there is no native XOR operator in LogicNG.

But you can easily encode an XOR by negating the equivalence operator.

`FormulaFactory f = new FormulaFactory();`
`f.not(f.equivalence(formulaA, formulaB));`

**Comment by exander77** [comment]
@rouven-walter Equivalence seems to be binary only, so for my n-ary xor I probable need to chain several of them together.

**Comment by rouven-walter** [comment]
You can write a help method to construct the XOR:
```
public static Formula xor(Formula a, Formula b) {
  FormulaFactory f = a.factory();
  return f.not(f.equivalence(a, b));
}
```
And then use this `xor` method to build an n-ary xor like `xor(a, xor(b, xor(c, d)))`.
Since the XOR operation is associative the brackets do not matter here.

**Comment by d-bischoff** [comment]
Wait a second...

a xor (b xor (c xor d)) is not the same as EXO(a,b,c,d)!

for example is a=0 and b=c=d=1 then a xor (b xor (c xor d)) = 0 xor (1 xor (1 xor 1)) = 0 xor (1 xor 0)) =  0 xor 1 = 1

**Comment by exander77** [comment]
What is EXO?

**Comment by rouven-walter** [comment]
EXO means exactly-one, which is a commonly used constraint to express that exactly one variable of a set of variable has to be true.

Depending on what exactly you want to achieve by an n-ary XOR it can be interpreted in two ways:
- A cascade of XOR operations `xor(a, xor(b, xor(c, d)))` which semantically evaluates to true if the number of true assigned variables is odd. 
- Or, generalizing the idea of the binary xor "one of two has to be chosen exclusively": "Choose one of `n` elements exclusivley", which can be encoded with an exactly-one constraint as @d-bischoff  mentioned.

In LogicNG you can represent such an excatly-one constraint using a pseudo-boolean constraint `formulaFactory.exo(variables)` or by encoding it directly as Boolean proposition with `formulaFactory.cc(CType.EQ, 1, variables)`.

**Comment by exander77** [comment]
What I mean is what you call cascade xor: `a xor b xor c xor d = a xor (b xor (c xor d)`
I have such xors with large number of terms. Even more than 10000.
