### ISSUE TITLE
Pseudo-Boolean Constraint toString into Parser Roundtrip does not work.

### ISSUE THREAD

**Issue by d-bischoff** [logic-ng/LogicNG#3]
If i parse a pseudo boolean constraint like

1 * A + 1 * B = 1 

it works. If I then print this with toString() it becomes

A + B = 1

which can not be parsed anymore.

I believe that output should be parseable again. And it is in all other cases.

**Comment by czengler** [comment]
Absolutely right.  The question ist: should 

(1) the parser be able to parse A + B = 1 or should 
(2) the toString() be 1 * A + 1 * B = 1.

(2) is very easy to implement, (1) would be more elegant to read. Any preferences?

**Comment by d-bischoff** [comment]
Well yes indeed. Exactly my thinking. 

Which probably already answers your question. I would prefere Option 1, but as a work around 2 is also fine. Would you agree?

**Comment by czengler** [comment]
OK. I went for the elegant solution :) This will be part of Release 1.1.  You can test the implementation in the `release_1.1` branch. Please give feedback, if everything works as expected.

**Comment by d-bischoff** [comment]
Will do. Thanks!

**Comment by d-bischoff** [comment]
I have yet to find any problems related to the new parser. Thanks again.
