### ISSUE TITLE
Add JavaDoc to "phase"

### ISSUE THREAD

**Issue by koppor** [logic-ng/LogicNG#30]
I am reading https://github.com/logic-ng/LogicNG#first-steps:

> `final Literal notC = f.literal("C", false);`

The documentation states that phase is a Boolean parameter. There is no documentation on the phase in `README.md` and not at the JavaDoc of `literal`.

I wonder why

a) phase is not en enum? An enum makes the possibilities clear. Currently with `false` I don't know whether there is no phase processing, if its a phase, where all variables are false, an initialization phase, ... - Reading the code I would have set it to `true`, but I am not sure.

b) There is no `literal` creator without any phase parameter (and then setting a default phase)

Would is be, additionally, possible to describe the `phase` in the README.md file?

(Issue created in my the context of my free-time project JabRef)

**Comment by czengler** [comment]
A *literal* in Boolean Algebra is a positive or negated variable - so it always has a phase - for a positive literal it is 'true' for a negative literal it is 'false'. Another word for *phase* would be *polarity* which makes it even more clear, that a literal must have a polarity.  

If you know, that you have a positive `Literal`, you can however create a `Variable` which does not require the `phase` parameter but only the name (and then constructs a positive literal).

In the upcoming LogicNG 2.0 perhaps we could document this fact in the `Literal` more clearly ;)

**Comment by koppor** [comment]
Thank you for the explanation. WikiPedia also talks about "polarity". Thus, I would recommend to rename `phase` to `polarity` (and keep the Boolean type)

![grafik](https://user-images.githubusercontent.com/1366654/85754348-45b26b00-b70d-11ea-8ec2-d3f75c3087c9.png)

https://en.wikipedia.org/wiki/Literal_(mathematical_logic)

**Comment by koppor** [comment]
I am still thinking, whether one should be forced to always state whether it is positive or negative. I would assume the default case is "positive", thus offer an additional method without a Boolean parameter.

**Comment by czengler** [comment]
"polarity" and "phase" can be used interchangeable - in our line of research, i.e. SAT Solving "phase" is the more common variant and whole techniques like "phase saving" are named thereafter - (c.f. e.g. https://resources.mpi-inf.mpg.de/departments/rg1/conferences/vtsa12/slides/biere/Biere-VTSA12-talk.pdf) . Therefore we do not see any reason to rename this attribute. And as stated above: a literal *always* has a phase, a positive literal is a plain variable - and can be generated without a phase.

We try to break backwards compatibility of LogicNG only when absolutely necessary, since it is used by  many major companies in industrial critical applications with systems with hundreds of thousands lines of code and thousands of different calls to LogicNG methods - therefore renaming such a central concept as 'phase' would imply massive refactoring effort in dozens of projects.

**Comment by koppor** [comment]
In this case, compatibility is the code comment compatbilitiy. It is still binary compatible.

I think, it would help to add some more description (JavaDoc) on it. Maybe just putting the synonmy there and a little usage example.

I used the library in my context as programmer. I was expecting the library building an AST similar to `or(not(a), b)` - thus `not` being a function. With the current API, it feels more like `or((a, negated), (b, not negated))`, which is strange for me.

I am not sure about your target user group. In University of Stuttgart teaching and research I never heared "phase". But I only leanred logics, theoretical computer science, petri nets, model checking ([Javier Esparza](https://www7.in.tum.de/~esparza/)), published papers applying [Prolog](https://en.wikipedia.org/wiki/Prolog) and an LTL solver ([LoLa](https://www7.in.tum.de/~schulzef/2014-06-13-Karsten-Wolf.pdf)). I also liked [CTL](https://en.wikipedia.org/wiki/Computation_tree_logic) very much.  Seems to be a different group of researchers than the ones involved in LogicNG. Not sure whether I am a target group and whether there are others with a similar background wanting to use LogicNG.

Since I assume there are other users around there who might be confused by `phase`, I am proposing to add more JavaDoc. I would even suggest to comment extensively as outlined in [Java by Comparison](https://media.pragprog.com/titles/javacomp/examples.pdf). - If it is "only" at the construction of literals, it would be fine for me. For me, this was really the hardest part of the library up to now.

**Comment by czengler** [comment]
You can always use the `not` function in LogicNG with a variable - so you never have to construct a literal explicitly :)
You can write your example with
```
final FormulaFactory f = new FormulaFactory();
final Formula formula = f.or(f.not(f.variable("a")), f.variable("b"));
```
Internally the `f.not(f.variable("a"))` is stored as a literal with negative phase.

The main developers of LogicNG all have their PhDs in Automated Reasoning and SAT Solving - therefore we naturally stick to the terminology mainly used in our field.

But let's not discuss about syntax - we will add a comment in the next version of LogicNG to clarify things.
