### ISSUE TITLE
Improve discoverability of features

### ISSUE THREAD

**Issue by rohte** [logic-ng/LogicNG#32]
Currently the only documentation apart from JavaDoc is the "Getting Started" section in the README. As JavaDoc is great when you know something exists but terrible if you don't it would be great to have a way to learn about features.
So for example I just learned about the `Anonymizer` and the `BackboneSimplifier` by looking through closed issues. This is not the best experience.
Even a list with features and classnames would be good.

**Comment by czengler** [comment]
Very good point ineed :) Since there is an increasing interest in LogicNG we will start such an overview of features in the Wiki in upcoming weeks!  Thank you very much for your suggestion.

**Comment by TiMauzi** [comment]
Maybe as a follow-up question: Why is there a cnf and nnf, but not a dnf function?

**Comment by rouven-walter** [comment]
There are actually multiple DNF methods to transform a formula into a DNF:

- [Canonical DNF Enumeration](https://github.com/logic-ng/LogicNG/blob/master/src/main/java/org/logicng/transformations/dnf/CanonicalDNFEnumeration.java)
- [DNF Factorization](https://github.com/logic-ng/LogicNG/blob/master/src/main/java/org/logicng/transformations/dnf/DNFFactorization.java)
- [BDD DNF Transformation](https://github.com/logic-ng/LogicNG/blob/master/src/main/java/org/logicng/transformations/dnf/BDDDNFTransformation.java)

But these are not directly accessible via the methods of a formula instance. Instead, you have to call the transformation method on a formula. E.g. `formula.transform(new DNFFactorization())`.

**Comment by rohte** [comment]
Just wanted to note that I appreciate the effort that went into populating the wiki. I have only gotten to read through a small portion so far, but this is a huge improvement. Thank you.

**Comment by czengler** [comment]
The documentation is now complete.
