### ISSUE TITLE
[bug] Error when exporting single-clause cnf formula to dimacs file

### ISSUE THREAD

**Issue by tnstrssnr** [logic-ng/LogicNG#33]
``FormulaDimacsFileWriter.write()`` produces a wrong .cnf file when exporting a formula that consists of a single clause with multiple literals. The formula is wrongfully split into multiple clauses that each contain one literal, effectively turning the disjunction into a conjunction.

**Faulty testcase:**
The expected .cnf file  (src/test/resources/writers/formulas-dimacs/f4_f.cnf) for the testcase formula f4 (``~(a & b) | b & ~c`` or as cnf: `` ~a | ~b | ~c``) in ``FormulaDimacsFileWriterTest.testFormulas()`` is wrong, which hides this bug when executing the test suite.

**Steps to  reproduce:**
- execute test method ``FormulaDimacsFileWriterTest.testFormulas()``
- the testcase formula f4 has cnf `` ~a | ~b | ~c``
- resulting dimacs .cnf file (src/test/resources/writers/temp/f4_f.cnf) is:
````
p cnf 3 3
-3  0
-1  0
-2  0
````
when it should be
````
p cnf 3 1
-1 -2 -3  0
````

**Comment by czengler** [comment]
Thank you very much for your bug report and the fix!

I merged the PR into the development branch and it will be releases with the next patch version of LogicNG.  If you need it released urgently, feel free to drop me a mail and we can release the version in a timely manner.

Best regards,
Christoph.

**Comment by rouven-walter** [comment]
Release 2.1.0 contains the fix.
