### ISSUE TITLE
What are valid variable names (for parsing)?

### ISSUE THREAD

**Issue by rohte** [logic-ng/LogicNG#37]
I encountered a ParserException due to an invalid character (`.`) when parsing a formula, which triggered this question. I could not find an answer in the documentation. Through tests I found out that underscores are supported.
Are other special characters supported?

**Comment by rouven-walter** [comment]
For the standard parser variable names must match the regular expression `[A-Za-z0-9_@][A-Za-z0-9_]*` (see [ANTLR grammar](https://github.com/logic-ng/LogicNG/blob/master/src/main/antlr/LogicNGPropositional.g4)). That means, only underscore is allowed as special character. Symbol `@` is allowed _only_ at the start of a variable name. Other than that, no special characters are allowed.

**Comment by rohte** [comment]
Thank you for the answer.
