### ISSUE TITLE
Please support or (<|>) Deriver?

### ISSUE THREAD

**Issue by oriming** [logic-ng/LogicNG#56]
In the project's business scenario, three derivations are used, namely =>,<=>,<|>, the first two LoginNGs are supported, XOR <|> It seems that I don't support it now. What should I do?

**Comment by SHildebrandt** [comment]
Hi! There are several reasons why we decided not to support XOR (one of which is that its meaning with more than two operands is not intuitive for many people).
If you create the formulas directly, you can formulate `a XOR b` as `f.and(f.or(f.variable("a"), f.variable("b")), f.or(f.literal("a", false), f.literal("b", false)))`. If you need a parser, you will probably need to copy and adjust one of our parsers or write your own.

**Comment by oriming** [comment]
Got it, thank you.😊
