### ISSUE TITLE
Formula immutable? 

### ISSUE THREAD

**Issue by cortex42** [logic-ng/LogicNG#7]
Schönen guten Tag zusammen,

ich hatte es Steffen neulich mal per Skype angekündigt und jetzt hier das passende Issue. Im Commit 1e7e0013206573750d12e9c5e9590e36a51fd51f haben wir eine Klasse eingecheckt die aus unserer Sicht einen Bug produziert.

Wir haben versucht das ganze möglicht minimal zu machen, soll heißen, der Code tut eigentlich nichts sinnvolles mehr und wir haben möglichst viel weggelassen. Was jetzt übrig ist sollte schon fast minimal sein.

Was passiert im Grunde?:
Wir basteln Formeln hin und her zusammen und bauen neue, Formula ist ja meines Wissens nach zunächst mal immutable. Dann wollen wir aus einer Formel eine neue berechnen indem wir Teile aus der bisherigen Formel rausstreichen. Dabei gelingt es uns (sollte es das?) die ursprüngliche Formel zu verändern indem wir ihre f.literals() verändern. Das allein ist ja schon unschön.

Dann verlassen wir die ganze Methode und machen einen Äquivalenzcheck auf zwei anderen Formeln. LogicNG sagt dann am Ende das Z = Z & ~X eine Tautologie sei. 

Guckt euch das Beispiel mal an, wir haben echt lange nach dem Problem gesucht und haben für unseren Fall jetzt auch einen Fix, aber so wahnsinnig intuitiv ist das alles für uns nicht was da abläuft.

Wenn man auf Java8 umstellt lässt sich der Bug auch mit Streams und Lambdas erzeugen, könnte man auch gleich mal angucken was da passiert.

Liebe Grüße,
Daniel und Ivo

**Comment by czengler** [comment]
Hallo zusammen,

Das Problem ist, dass die `Literals` Klasse in der Methode `literals()` einen gecachten Wert zurückgibt - keine Kopie. Wenn ihr jetzt in diesem Set wirklich Dinge löscht, dann passiert das in diesem gecachten Wert - und damit entsteht eine ungültige Formel, nämlich ein Literal `x`, dessen `literals()` Methode eine leere Menge zurück gibt.  Ab dem Zeitpunkt kann alles mögliche passieren.

Der gecachte Wert ist natürlich aus Performance Gründen drin, damit nicht jedesmal ein neues `SortedSet` erzeugt wird. Meine Lösung wäre also jetzt, dass wir an der Stelle ein `UnmodifiableSortedSet` zurückgeben, damit der Benutzer ordentlich mitbekommt, dass er gerade etwas böses macht. Ebenso werde ich es in der JavaDoc festhalten, dass diese Werte nur gelesen werden können. Gleiches werde ich auch bei der `variables()` Methode machen, da kann das nämlich auch passieren.

**Comment by d-bischoff** [comment]
Hallo Christoph,

das ging schnell :D 

Herzlichen Dank für die schnelle Antwort und den Fix. Die eigentliche Problemlösung haben wir zwar schon, aber die Stelle kam uns "gefährlich" vor.

Liebe Grüße,
Daniel

**Comment by d-bischoff** [comment]
Ich war mal so frei das im Code für die beiden Methoden zu machen. Javadoc Ergänzung fehlt.

**Comment by czengler** [comment]
Super. Vielen Dank. Schaue ich mir an.  Wir wollen nächste Woche eh ein neues Release machen - dann kommt es da gleich mit rein.

**Comment by czengler** [comment]
Merge request ist in den release1.2 branch gemerged.
